openapi: 3.0.3
info:
  title: Auth API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: /api/v1
security:
  - bearerAuth: []

paths:
  /login:
    post:
      operationId: login
      summary: 登录
      tags:
        - Auth
      security: [] # 显式设置为空，覆盖全局 security
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: 用户名或密码错误

  /logout:
    get:
      operationId: logout
      summary: 注销登录
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        "204":
          description: 注销成功，无返回内容
        "401":
          description: 未授权
        default:
          description: 未知错误
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /me:
    get:
      operationId: getCurrentUser
      summary: 获取当前用户信息
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        "200":
          description: 当前用户信息
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: 未授权
        default:
          description: 未知错误
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码
      required:
        - username
        - password

    User:
      type: object
      properties:
        uid:
          type: integer
          description: 用户ID
        username:
          type: string
          description: 用户名
        role:
          type: string
          description: 角色
      required:
        - uid
        - username

    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: 认证令牌
        user:
          $ref: "#/components/schemas/User"
      required:
        - token
        - user
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
